### ISSUE TITLE
Saying sentences consisting of only one word from among known common nouns throws an Argument Out of Range Exception

### ISSUE THREAD

**Issue by hecateeeee** [ianhorswill/Imaginarium-old#13]
Tested with default "cats" generator with no additional items in the KB.

If you say, e.g., "cat" or "cats", Imaginarium reports an AOORE.
Screenie:
![imaginarium_bug](https://user-images.githubusercontent.com/7151453/80389964-6b3c0900-8871-11ea-8ec3-77bcd0a72149.png)

If you say common nouns (e.g., "footballs") that it doesn't know, it merely reports confusion. If you add a new common noun (e.g., "footballs are cool"), subsequently saying nonsense sentences using those common nouns (e.g., "football") throws the AOORE.

Given that saying nonsense sentences like "is cool" generates a bunch of helpful tips about how to write sentences, the AOORE is probably something that should be hidden, and replaced with helpful tips about how to write sentences that start with, e.g., "cats".

**Comment by ianhorswill** [comment]
Fixed.  Bless you!
