### ISSUE TITLE
Imagining a name from an empty names file gives a (reasonable) divide by zero exception

### ISSUE THREAD

**Issue by hecateeeee** [ianhorswill/Imaginarium-old#14]
Adding even a single name to the file fixes this problem. Perhaps catch empty files (names or .gens) and provide a helpful message?

Contents of pantheon.gen:
```
Gods are vengeful, cruel, or benevolent
A god has a name from godnames
```

Contents of godnames.txt:
```
```

Command: `imagine a god`
Screenie from error:
![imaginarium_empty_names](https://user-images.githubusercontent.com/7151453/80391327-30d36b80-8873-11ea-832e-8eabc0c2ed43.png)

**Comment by ianhorswill** [comment]
Fixed.  Thanks!
