### ISSUE TITLE
Declaring "kinds of X" in multiple chunks gives "Unknown sentence pattern"

### ISSUE THREAD

**Issue by hecateeeee** [ianhorswill/Imaginarium-old#17]
Example code below run in the "Cats" default generator. An analagous error occurs when loading code from a generator file.

Running
```
resistance to fire and resistance to wind are kinds of resistances
```
gives typical feedback about "learning the common noun..."

Subsequently running
```
resistance to disease is a kind of resistance
```
Gives "Uh oh. I got confused..."

Similarly, running
```
resistance to fire and resistance to wind are kinds of resistances
resistance to disease and resistance to fear are kinds of resistances
```
or
```
resistance to fire is a kind of resistance
resistance to disease and resistance to fear are kinds of resistances
```
gives the same error, so it looks like it's not, e.g., getting tripped up by plurals or something.

Adding all of the kinds of in one statement runs fine, so it looks like it's struggling to add new "kinds of" after the first set of "kinds of" has been added.

**Comment by ianhorswill** [comment]
That's a kind of problem that's baked into the design of the parser.  It can't tolerate nouns that are prefixes of other nouns.  So what's happening there is that when it sees "resistance to fire" it correctly parses it as a noun.  Then it sees resistances and correctly parses it as another noun, without noticing that it's a prefix of "resistance to disease" (should probably fix that).  Then, when you say "resistance to fire is a kind of resistance", it starts parsing "resistance to fire", gets through the first word and says "oh, this is a noun I know" and assumes it has the whole noun.  So then parsing the rest of the pattern fails.
