### ISSUE TITLE
Objects with adjectives behave weirdly when kinds try to overwrite

### ISSUE THREAD

**Issue by OwenJanssen** [ianhorswill/Imaginarium-old#22]
This first issue arrises if every kind is given a specific adjective:
![image](https://user-images.githubusercontent.com/67287024/86407506-2d999900-bc83-11ea-81fb-9d36980671d4.png)
![image](https://user-images.githubusercontent.com/67287024/86407511-2f635c80-bc83-11ea-9e05-90328a3b5db1.png)
When every kind but one is given an adjective this issue arises:
![image](https://user-images.githubusercontent.com/67287024/86407655-72bdcb00-bc83-11ea-9ab7-4f5ba417fa7f.png)
![image](https://user-images.githubusercontent.com/67287024/86407665-75b8bb80-bc83-11ea-94d5-47093c67ecbc.png)

**Comment by ianhorswill** [comment]
Fixed.  But you will have to first say `a weapon has a range between 1 and 50`.  Having done that, you can then specify narrower ranges for different special cases.
